name: dighum
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - pandas=2.0
  - "numpy<2.0"
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy=1.11
  - gensim
  - nltk
  - spacy
  - networkx
  - beautifulsoup4
  - requests
  - tqdm
  - ipykernel
  - bokeh=3.3
  - pip
  - pip:
    - transformers
    - torch
    - pydantic
    - adjusttext
    - "pyldavis==3.4.1"
    - "numexpr<2.10"
    - inflect
    - bertopic
    - gdown